//
// Created by cameronearle on 2/21/17.
//

#include "Configuration.hpp"

std::string Configuration::hash() {
    return
    "CONFIG#"
    + ("goalProcDeviceNumber:" + std::to_string(goalProcDeviceNumber)) + ","
    + ("gearProcDeviceNumber:" + std::to_string(gearProcDeviceNumber)) + ","
    + ("goalProcFOV:" + std::to_string(goalProcFOV)) + ","
    + ("gearProcFOV:" + std::to_string(gearProcFOV)) + ","
    + ("goalProcFocalLength:" + std::to_string(goalProcFocalLength)) + ","
    + ("gearProcFocalLength:" + std::to_string(gearProcFocalLength)) + ","
    + ("streamDeviceNumber:" + std::to_string(streamDeviceNumber)) + ","
    + ("networkBasePort:" + std::to_string(networkBasePort)) + ","
    + ("showDebugWindows:" + std::to_string(showDebugWindows)) + ","
    + ("showDebugText:" + std::to_string(showDebugText)) + ","
    + ("runDebugFunctions:" + std::to_string(runDebugFunctions)) + ","
    + ("streamCompression:" + std::to_string(streamCompression)) + ","
    + ("goalProcHLower:" + std::to_string(goalProcHLower)) + ","
    + ("goalProcSLower:" + std::to_string(goalProcSLower)) + ","
    + ("goalProcVLower:" + std::to_string(goalProcVLower)) + ","
    + ("goalProcHUpper:" + std::to_string(goalProcHUpper)) + ","
    + ("goalProcSUpper:" + std::to_string(goalProcSUpper)) + ","
    + ("goalProcVUpper:" + std::to_string(goalProcVUpper)) + ","
    + ("gearProcHLower:" + std::to_string(gearProcHLower)) + ","
    + ("gearProcSLower:" + std::to_string(gearProcSLower)) + ","
    + ("gearProcVLower:" + std::to_string(gearProcVLower)) + ","
    + ("gearProcHUpper:" + std::to_string(gearProcHUpper)) + ","
    + ("gearProcSUpper:" + std::to_string(gearProcSUpper)) + ","
    + ("gearProcVUpper:" + std::to_string(gearProcVUpper)) + ","
    + ("goalMinArea:" + std::to_string(goalMinArea)) + ","
    + ("goalMinPerimeter:" + std::to_string(goalMinPerimeter)) + ","
    + ("goalMinWidth:" + std::to_string(goalMinWidth)) + ","
    + ("goalMaxWidth:" + std::to_string(goalMaxWidth)) + ","
    + ("goalMinHeight:" + std::to_string(goalMinHeight)) + ","
    + ("goalMaxHeight:" + std::to_string(goalMaxHeight)) + ","
    + ("goalMinSolidity:" + std::to_string(goalMinSolidity)) + ","
    + ("goalMaxSolidity:" + std::to_string(goalMaxSolidity)) + ","
    + ("goalMinVertices:" + std::to_string(goalMinVertices)) + ","
    + ("goalMaxVertices:" + std::to_string(goalMaxVertices)) + ","
    + ("goalMinRatio:" + std::to_string(goalMinRatio)) + ","
    + ("goalMaxRatio:" + std::to_string(goalMaxRatio)) + ","
    + ("gearMinArea:" + std::to_string(gearMinArea)) + ","
    + ("gearMinPerimeter:" + std::to_string(gearMinPerimeter)) + ","
    + ("gearMinWidth:" + std::to_string(gearMinWidth)) + ","
    + ("gearMaxWidth:" + std::to_string(gearMaxWidth)) + ","
    + ("gearMinHeight:" + std::to_string(gearMinHeight)) + ","
    + ("gearMaxHeight:" + std::to_string(gearMaxHeight)) + ","
    + ("gearMinSolidity:" + std::to_string(gearMinSolidity)) + ","
    + ("gearMaxSolidity:" + std::to_string(gearMaxSolidity)) + ","
    + ("gearMinVertices:" + std::to_string(gearMinVertices)) + ","
    + ("gearMaxVertices:" + std::to_string(gearMaxVertices)) + ","
    + ("gearMinRatio:" + std::to_string(gearMinRatio)) + ","
    + ("gearMaxRatio:" + std::to_string(gearMaxRatio)) + ","
    + ("goalProcCameraBrightness:" + std::to_string(goalProcCameraBrightness)) + ","
    + ("goalProcCameraContrast:" + std::to_string(goalProcCameraContrast)) + ","
    + ("goalProcCameraSaturation:" + std::to_string(goalProcCameraSaturation)) + ","
    + ("goalProcCameraHue:" + std::to_string(goalProcCameraHue)) + ","
    + ("goalProcCameraAutoWB:" + std::to_string(goalProcCameraAutoWB)) + ","
    + ("goalProcCameraExposure:" + std::to_string(goalProcCameraExposure)) + ","
    + ("goalProcCameraAutoGain:" + std::to_string(goalProcCameraAutoGain)) + ","
    + ("goalProcCameraGain:" + std::to_string(goalProcCameraGain)) + ","
    + ("goalProcCameraVFlip:" + std::to_string(goalProcCameraVFlip)) + ","
    + ("goalProcCameraHFlip:" + std::to_string(goalProcCameraHFlip)) + ","
    + ("goalProcCameraManualExposure:" + std::to_string(goalProcCameraManualExposure)) + ","
    + ("gearProcCameraBrightness:" + std::to_string(gearProcCameraBrightness)) + ","
    + ("gearProcCameraContrast:" + std::to_string(gearProcCameraContrast)) + ","
    + ("gearProcCameraSaturation:" + std::to_string(gearProcCameraSaturation)) + ","
    + ("gearProcCameraHue:" + std::to_string(gearProcCameraHue)) + ","
    + ("gearProcCameraAutoWB:" + std::to_string(gearProcCameraAutoWB)) + ","
    + ("gearProcCameraExposure:" + std::to_string(gearProcCameraExposure)) + ","
    + ("gearProcCameraAutoGain:" + std::to_string(gearProcCameraAutoGain)) + ","
    + ("gearProcCameraGain:" + std::to_string(gearProcCameraGain)) + ","
    + ("gearProcCameraVFlip:" + std::to_string(gearProcCameraVFlip)) + ","
    + ("gearProcCameraHFlip:" + std::to_string(gearProcCameraHFlip)) + ","
    + ("gearProcCameraManualExposure:" + std::to_string(gearProcCameraManualExposure)) + ","
    + ("goalStreamCameraBrightness:" + std::to_string(goalStreamCameraBrightness)) + ","
    + ("goalStreamCameraContrast:" + std::to_string(goalStreamCameraContrast)) + ","
    + ("goalStreamCameraSaturation:" + std::to_string(goalStreamCameraSaturation)) + ","
    + ("goalStreamCameraHue:" + std::to_string(goalStreamCameraHue)) + ","
    + ("goalStreamCameraAutoWB:" + std::to_string(goalStreamCameraAutoWB)) + ","
    + ("goalStreamCameraExposure:" + std::to_string(goalStreamCameraExposure)) + ","
    + ("goalStreamCameraAutoGain:" + std::to_string(goalStreamCameraAutoGain)) + ","
    + ("goalStreamCameraGain:" + std::to_string(goalStreamCameraGain)) + ","
    + ("goalStreamCameraVFlip:" + std::to_string(goalStreamCameraVFlip)) + ","
    + ("goalStreamCameraHFlip:" + std::to_string(goalStreamCameraHFlip)) + ","
    + ("goalStreamCameraManualExposure:" + std::to_string(goalStreamCameraManualExposure)) + ","
    + ("gearStreamCameraBrightness:" + std::to_string(gearStreamCameraBrightness)) + ","
    + ("gearStreamCameraContrast:" + std::to_string(gearStreamCameraContrast)) + ","
    + ("gearStreamCameraSaturation:" + std::to_string(gearStreamCameraSaturation)) + ","
    + ("gearStreamCameraHue:" + std::to_string(gearStreamCameraHue)) + ","
    + ("gearStreamCameraAutoWB:" + std::to_string(gearStreamCameraAutoWB)) + ","
    + ("gearStreamCameraExposure:" + std::to_string(gearStreamCameraExposure)) + ","
    + ("gearStreamCameraAutoGain:" + std::to_string(gearStreamCameraAutoGain)) + ","
    + ("gearStreamCameraGain:" + std::to_string(gearStreamCameraGain)) + ","
    + ("gearStreamCameraVFlip:" + std::to_string(gearStreamCameraVFlip)) + ","
    + ("gearStreamCameraHFlip:" + std::to_string(gearStreamCameraHFlip)) + ","
    + ("gearStreamCameraManualExposure:" + std::to_string(gearStreamCameraManualExposure))
    ;
}