//
// Created by cameronearle on 2/21/17.
//

#include "Configuration.hpp"

std::string Configuration::hash() {
    return
    "CONFIG#"
    + ("goalProcDeviceNumber:" + std::to_string(goalProcDeviceNumber)) + ","
    + ("gearProcDeviceNumber:" + std::to_string(gearProcDeviceNumber)) + ","
    + ("goalProcFOV:" + std::to_string(goalProcFOV)) + ","
    + ("gearProcFOV:" + std::to_string(gearProcFOV)) + ","
    + ("streamDeviceNumber:" + std::to_string(streamDeviceNumber)) + ","
    + ("networkBasePort:" + std::to_string(networkBasePort)) + ","
    + ("showDebugWindows:" + std::to_string(showDebugWindows)) + ","
    + ("showDebugText:" + std::to_string(showDebugText)) + ","
    + ("runDebugFunctions:" + std::to_string(runDebugFunctions)) + ","
    + ("streamCompression:" + std::to_string(streamCompression)) + ","
    + ("goalProcHBase:" + std::to_string(goalProcHBase)) + ","
    + ("goalProcSBase:" + std::to_string(goalProcSBase)) + ","
    + ("goalProcVBase:" + std::to_string(goalProcVBase)) + ","
    + ("goalProcHRange:" + std::to_string(goalProcHRange)) + ","
    + ("goalProcSRange:" + std::to_string(goalProcSRange)) + ","
    + ("goalProcVRange:" + std::to_string(goalProcVRange)) + ","
    + ("gearProcHBase:" + std::to_string(gearProcHBase)) + ","
    + ("gearProcSBase:" + std::to_string(gearProcSBase)) + ","
    + ("gearProcVBase:" + std::to_string(gearProcVBase)) + ","
    + ("gearProcHRange:" + std::to_string(gearProcHRange)) + ","
    + ("gearProcSRange:" + std::to_string(gearProcSRange)) + ","
    + ("gearProcVRange:" + std::to_string(gearProcVRange)) + ","
    + ("goalProcAspect:" + std::to_string(goalProcAspect)) + ","
    + ("gearProcAspect:" + std::to_string(gearProcAspect)) + ","
    + ("goalProcAspectRange:" + std::to_string(goalProcAspectRange)) + ","
    + ("gearProcAspectRange:" + std::to_string(gearProcAspectRange)) + ","
    + ("goalProcCameraBrightness:" + std::to_string(goalProcCameraBrightness)) + ","
    + ("goalProcCameraContrast:" + std::to_string(goalProcCameraContrast)) + ","
    + ("goalProcCameraSaturation:" + std::to_string(goalProcCameraSaturation)) + ","
    + ("goalProcCameraHue:" + std::to_string(goalProcCameraHue)) + ","
    + ("goalProcCameraAutoWB:" + std::to_string(goalProcCameraAutoWB)) + ","
    + ("goalProcCameraExposure:" + std::to_string(goalProcCameraExposure)) + ","
    + ("goalProcCameraAutoGain:" + std::to_string(goalProcCameraAutoGain)) + ","
    + ("goalProcCameraGain:" + std::to_string(goalProcCameraGain)) + ","
    + ("goalProcCameraVFlip:" + std::to_string(goalProcCameraVFlip)) + ","
    + ("goalProcCameraHFlip:" + std::to_string(goalProcCameraHFlip)) + ","
    + ("goalProcCameraManualExposure:" + std::to_string(goalProcCameraManualExposure)) + ","
    + ("gearProcCameraBrightness:" + std::to_string(gearProcCameraBrightness)) + ","
    + ("gearProcCameraContrast:" + std::to_string(gearProcCameraContrast)) + ","
    + ("gearProcCameraSaturation:" + std::to_string(gearProcCameraSaturation)) + ","
    + ("gearProcCameraHue:" + std::to_string(gearProcCameraHue)) + ","
    + ("gearProcCameraAutoWB:" + std::to_string(gearProcCameraAutoWB)) + ","
    + ("gearProcCameraExposure:" + std::to_string(gearProcCameraExposure)) + ","
    + ("gearProcCameraAutoGain:" + std::to_string(gearProcCameraAutoGain)) + ","
    + ("gearProcCameraGain:" + std::to_string(gearProcCameraGain)) + ","
    + ("gearProcCameraVFlip:" + std::to_string(gearProcCameraVFlip)) + ","
    + ("gearProcCameraHFlip:" + std::to_string(gearProcCameraHFlip)) + ","
    + ("gearProcCameraManualExposure:" + std::to_string(gearProcCameraManualExposure)) + ","
    + ("goalStreamCameraBrightness:" + std::to_string(goalStreamCameraBrightness)) + ","
    + ("goalStreamCameraContrast:" + std::to_string(goalStreamCameraContrast)) + ","
    + ("goalStreamCameraSaturation:" + std::to_string(goalStreamCameraSaturation)) + ","
    + ("goalStreamCameraHue:" + std::to_string(goalStreamCameraHue)) + ","
    + ("goalStreamCameraAutoWB:" + std::to_string(goalStreamCameraAutoWB)) + ","
    + ("goalStreamCameraExposure:" + std::to_string(goalStreamCameraExposure)) + ","
    + ("goalStreamCameraAutoGain:" + std::to_string(goalStreamCameraAutoGain)) + ","
    + ("goalStreamCameraGain:" + std::to_string(goalStreamCameraGain)) + ","
    + ("goalStreamCameraVFlip:" + std::to_string(goalStreamCameraVFlip)) + ","
    + ("goalStreamCameraHFlip:" + std::to_string(goalStreamCameraHFlip)) + ","
    + ("goalStreamCameraManualExposure:" + std::to_string(goalStreamCameraManualExposure)) + ","
    + ("gearStreamCameraBrightness:" + std::to_string(gearStreamCameraBrightness)) + ","
    + ("gearStreamCameraContrast:" + std::to_string(gearStreamCameraContrast)) + ","
    + ("gearStreamCameraSaturation:" + std::to_string(gearStreamCameraSaturation)) + ","
    + ("gearStreamCameraHue:" + std::to_string(gearStreamCameraHue)) + ","
    + ("gearStreamCameraAutoWB:" + std::to_string(gearStreamCameraAutoWB)) + ","
    + ("gearStreamCameraExposure:" + std::to_string(gearStreamCameraExposure)) + ","
    + ("gearStreamCameraAutoGain:" + std::to_string(gearStreamCameraAutoGain)) + ","
    + ("gearStreamCameraGain:" + std::to_string(gearStreamCameraGain)) + ","
    + ("gearStreamCameraVFlip:" + std::to_string(gearStreamCameraVFlip)) + ","
    + ("gearStreamCameraHFlip:" + std::to_string(gearStreamCameraHFlip)) + ","
    + ("gearStreamCameraManualExposure:" + std::to_string(gearStreamCameraManualExposure))
    ;
}